# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "openITCOCKPIT-V3"
	config.vm.network "private_network", :type => 'dhcp', :name => "VirtualBox Host-Only Ethernet Adapter #2", :adapter => 2
	config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"
	config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2084
		vb.cpus = 2
	end
	config.vm.provision "shell", inline: <<-SHELL
		wget http://apt.open-itcockpit.com/A7D3EAFA.txt -q -O - | apt-key add -
		echo 'deb http://apt.open-itcockpit.com trusty main' > /etc/apt/sources.list.d/openitcockpit.list
		sudo apt-get update
		sudo apt-get install -y git expect samba-common samba vim htop tmux nfs-kernel-server
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password vagrant'
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password vagrant'
		sudo debconf-set-selections <<< 'openitcockpit-mysql mysql-server/root_password password vagrant'
		sudo debconf-set-selections <<< 'openitcockpit-mysql mysql-server/root_password_again password vagrant'

		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/dbconfig-install boolean true'
		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/app-password-confirm password vagrant'
		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/admin-pass password vagrant'
		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/mysql/app-pass password vagrant'
		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/password password vagrant'
		sudo debconf-set-selections <<< 'phpmyadmin phpmyadmin/password-confirm password vagrant'
		sudo apt-get -y install mysql-server openitcockpit{,-nagios,-ndoutils,-npcd}
		git clone https://github.com/it-novum/vagrantboxes
		cd vagrantboxes/openITCOCKPIT_V3-dev
		sudo chmod +x install.sh
		sudo chmod +x finished.sh
		sudo -E ./install.sh
		./finished.sh
	SHELL
end
